/// Flutter icons Tomisin
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Tomisin
///      fonts:
///       - asset: fonts/Tomisin.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter_web/widgets.dart';

class Tomisin {
  Tomisin._();

  static const _kFontFam = 'Tomisin';

  static const IconData account_balance = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData airline_seat_legroom_extra = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData account_box = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData airline_seat_legroom_reduced = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData audiotrack = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData backspace = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData gmail = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData linkedin = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData facebook_circled = const IconData(0xf051, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xf052, fontFamily: _kFontFam);
  static const IconData github_circled_alt2 = const IconData(0xf056, fontFamily: _kFontFam);
}
